osx_image: xcode8.3

dist: trusty
sudo: false

language: node_js
node_js: "10"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - linux
  - osx

cache:
  yarn: true
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

install:
  - yarn install

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then CI=false yarn electron:release; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then CI=false yarn electron:release -- --mac --win; fi

deploy:
  api_key: $GH_TOKEN
  provider: releases
  file_glob: true
  file: "dist/*"
  skip_cleanup: true
  on:
    tags: false
    repo: rubenbase/bos-cli
    branch: master 

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
